### ISSUE TITLE
about rename

### ISSUE THREAD

**Issue by berkaytheunicorn** [andrefgneves/meteor-iconfont#1]
```
    webfont:
      icons:
        src: 'dev/icons/svg/*.svg'
        dest: 'public/icons'
        destCss: 'dev/stylus'
        options:
          font: 'icons'
          rename: (name) ->
            class_name = name.toLowerCase()
            class_name = class_name.replace("i_", "")
            remove_path = class_name.lastIndexOf('/')
            class_name = class_name.substr((remove_path + 1))
            return class_name
          syntax: "bootstrap"
          hashes: false
          engine:"node"
          template: 'dev/icons/template.css'
          templateOptions:
            baseClass: "icon"
            classPrefix: "icon-"
            mixinPrefix: "icon-"
          stylesheet: "styl"
          relativeFontPath: "/icons"
          embed: ['woff', 'ttf', 'svg', 'eot']
```

coffee

hi I'm trying to migrate to meteor.js and I used to use like this in grunt file.
but your options is only json and I can't use like this. Is there any workarounds ?
